### ISSUE TITLE
Support additionnal SSL attributes

### ISSUE THREAD

**Issue by ponceta** [opengisch/qgis-pg-service-parser-plugin#49]
Here's an evolution idea from one of our TEKSI users :

Support additional SSL attributes :

- [ ] sslrootcert=path_to_rootrcert/foo.crt
- [ ] sslcert=path_to_sslcert/bar.crt
- [ ] sslkey=path_to_sslkey/foobar.key

Ref issue :

https://github.com/teksi/wastewater/issues/393

Comment :
We should take care that QGIS vision of pg_service configuration is on the same line too.

**Comment by gacarrillor** [comment]
If urgent, note that you could manually add missing PG service settings as  new entries at https://github.com/opengisch/qgis-pg-service-parser-plugin/blob/0fecfea2a31f0c81d19577e832dae8389bef8728/pg_service_parser/conf/service_settings.py#L5

In that way, you can set them via the plugin dialog and they'll be transferred to your PG service file and read from it.

You could also create a PR with those new entries.

However, since the proposed settings correspond to file paths, it would be convenient to show proper file selection dialogs. That would require some development.

**Comment by ponceta** [comment]
@cymed this is now fixed in latest experimental, would you be able to try it and give us a feedback?

![Image](https://github.com/user-attachments/assets/1b4985e6-4e4b-4416-b3fd-810446c1cd0e)

**Comment by cymed** [comment]
The UI does what I wanted it to do, However, I cannot test fully as I get a PermissionError: [Errno 13] Permission denied. I am working on Windows

**Comment by ponceta** [comment]
Could you share the target folder on windows?`

Similar to :
https://github.com/opengisch/qgis-pg-service-parser-plugin/issues/57

**Comment by cymed** [comment]
It is not the same problem as in #57 as the folder exists:

```
PermissionError: [Errno 13] Permission denied: 'path\\to\\pg_service.conf'

Traceback (most recent call last):
  File "C:\Users/usr/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\pg_service_parser\gui\dlg_pg_service.py", line 345, in __update_service_clicked
    write_service(
  File "C:\Users/usr/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\pg_service_parser\core\pg_service_parser_wrapper.py", line 28, in write_service
    pgserviceparser.write_service(service_name, settings, conf_file_path)
  File "C:\Users/usr/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\pg_service_parser\libs\pgserviceparser\__init__.py", line 179, in write_service
    with open(conf_file_path or conf_path(), "w") as configfile:
```
